#!/bin/bash
echo "Checking for ghost directories and files..."
echo ""
echo "=== Directory structure ==="
ls -la ~/.task/hooks/ 2>/dev/null | grep priority || echo "No priority dir in hooks"
ls -la ~/.task/hooks/priority/ 2>/dev/null || echo "No ~/.task/hooks/priority/ directory"
echo ""
echo "=== Config files ==="
grep -r "hooks/priority" ~/.task/*.rc ~/.task/config/*.rc ~/.taskrc 2>/dev/null || echo "No hooks/priority in config files"
echo ""
echo "=== Taskwarrior aliases ==="
task show | grep -i "alias.*nn" || echo "No nn alias found"
echo ""
echo "=== Installed scripts ==="
ls -la ~/.task/scripts/ 2>/dev/null | grep nn || echo "No nn in scripts"
echo ""
echo "=== Where is nn? ==="
which nn 2>/dev/null || echo "nn not in PATH"
type nn 2>/dev/null || echo "nn not a shell function/alias"
